#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 24 17:37:26 COT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Global_Shaders.zip
enableShaders=false
